//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PratikAraBul.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AraBulEntities : DbContext
    {
        public AraBulEntities()
            : base("name=AraBulEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblHizmetKategori> tblHizmetKategori { get; set; }
        public virtual DbSet<tblHizmetler> tblHizmetler { get; set; }
        public virtual DbSet<tblBasliklar> tblBasliklar { get; set; }
        public virtual DbSet<tblAdmin> tblAdmin { get; set; }
        public virtual DbSet<tblPopularHizmet> tblPopularHizmet { get; set; }
    }
}
