
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PratikAraBul.Models.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tblBasliklar
{

    public int BaslikId { get; set; }

    public string MusteriHizmetleriBaslik { get; set; }

    public string HesaplamaAraclariBaslik { get; set; }

    public string KalanGünSayaciBaslik { get; set; }

    public Nullable<int> MarkaId { get; set; }



    public virtual tblHizmetler tblHizmetler { get; set; }

}

}
