
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PratikAraBul.Models.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class tblHizmetKategori
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblHizmetKategori()
    {

        this.tblHizmetler = new HashSet<tblHizmetler>();

    }


    public int Id { get; set; }

    public string KategoriAd { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblHizmetler> tblHizmetler { get; set; }

}

}
