//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PratikAraBul.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPopularHizmet
    {
        public int PopularId { get; set; }
        public string PopularAd { get; set; }
        public Nullable<int> HizmetId { get; set; }
    
        public virtual tblHizmetler tblHizmetler { get; set; }
    }
}
